// Generated by jextract

package dev.sudipsaha;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.util.Arrays;
import java.util.stream.Collectors;

import static java.lang.foreign.ValueLayout.JAVA_BYTE;

public class mylib_h {

    mylib_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();
    static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

    static void traceDowncall(String name, Object... args) {
         String traceArgs = Arrays.stream(args)
                       .map(Object::toString)
                       .collect(Collectors.joining(", "));
         System.out.printf("%s(%s)\n", name, traceArgs);
    }

    static MemorySegment findOrThrow(String symbol) {
        return SYMBOL_LOOKUP.find(symbol)
            .orElseThrow(() -> new UnsatisfiedLinkError("unresolved symbol: " + symbol));
    }

    static MethodHandle upcallHandle(Class<?> fi, String name, FunctionDescriptor fdesc) {
        try {
            return MethodHandles.lookup().findVirtual(fi, name, fdesc.toMethodType());
        } catch (ReflectiveOperationException ex) {
            throw new AssertionError(ex);
        }
    }

    static MemoryLayout align(MemoryLayout layout, long align) {
        return switch (layout) {
            case PaddingLayout p -> p;
            case ValueLayout v -> v.withByteAlignment(align);
            case GroupLayout g -> {
                MemoryLayout[] alignedMembers = g.memberLayouts().stream()
                        .map(m -> align(m, align)).toArray(MemoryLayout[]::new);
                yield g instanceof StructLayout ?
                        MemoryLayout.structLayout(alignedMembers) : MemoryLayout.unionLayout(alignedMembers);
            }
            case SequenceLayout s -> MemoryLayout.sequenceLayout(s.elementCount(), align(s.elementLayout(), align));
        };
    }

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.libraryLookup(System.mapLibraryName("myclib"), LIBRARY_ARENA)
            .or(SymbolLookup.loaderLookup())
            .or(Linker.nativeLinker().defaultLookup());

    public static final ValueLayout.OfBoolean C_BOOL = ValueLayout.JAVA_BOOLEAN;
    public static final ValueLayout.OfByte C_CHAR = ValueLayout.JAVA_BYTE;
    public static final ValueLayout.OfShort C_SHORT = ValueLayout.JAVA_SHORT;
    public static final ValueLayout.OfInt C_INT = ValueLayout.JAVA_INT;
    public static final ValueLayout.OfLong C_LONG_LONG = ValueLayout.JAVA_LONG;
    public static final ValueLayout.OfFloat C_FLOAT = ValueLayout.JAVA_FLOAT;
    public static final ValueLayout.OfDouble C_DOUBLE = ValueLayout.JAVA_DOUBLE;
    public static final AddressLayout C_POINTER = ValueLayout.ADDRESS
            .withTargetLayout(MemoryLayout.sequenceLayout(java.lang.Long.MAX_VALUE, JAVA_BYTE));
    public static final ValueLayout.OfInt C_LONG = ValueLayout.JAVA_INT;
    public static final ValueLayout.OfDouble C_LONG_DOUBLE = ValueLayout.JAVA_DOUBLE;

    private static class add {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            mylib_h.C_INT,
            mylib_h.C_INT,
            mylib_h.C_INT
        );

        public static final MemorySegment ADDR = mylib_h.findOrThrow("add");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int add(int a, int b)
     * }
     */
    public static FunctionDescriptor add$descriptor() {
        return add.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int add(int a, int b)
     * }
     */
    public static MethodHandle add$handle() {
        return add.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int add(int a, int b)
     * }
     */
    public static MemorySegment add$address() {
        return add.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int add(int a, int b)
     * }
     */
    public static int add(int a, int b) {
        var mh$ = add.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("add", a, b);
            }
            return (int)mh$.invokeExact(a, b);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class multiply {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            mylib_h.C_INT,
            mylib_h.C_INT,
            mylib_h.C_INT
        );

        public static final MemorySegment ADDR = mylib_h.findOrThrow("multiply");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int multiply(int a, int b)
     * }
     */
    public static FunctionDescriptor multiply$descriptor() {
        return multiply.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int multiply(int a, int b)
     * }
     */
    public static MethodHandle multiply$handle() {
        return multiply.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int multiply(int a, int b)
     * }
     */
    public static MemorySegment multiply$address() {
        return multiply.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int multiply(int a, int b)
     * }
     */
    public static int multiply(int a, int b) {
        var mh$ = multiply.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("multiply", a, b);
            }
            return (int)mh$.invokeExact(a, b);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

